### PR TITLE
[SC-241] refactor apache script

### PR DESCRIPTION
**Pull request by zaro0508**
remove apache scripts dependence on make_env_vars_file.sh which
will make the script simpler and make provisioning instances
faster.

### CODE REVIEW

**Review by ahayden — APPROVED** [review]
Looks good

**Review by brucehoff — CHANGES_REQUESTED** [review]
Looking at this script it's not immediately clear what it's for.  Could you add a comment? Something like:
```
This script is run on an EC2 instance upon start up to add its own address to the list of servers that the (reverse?? / forward??) proxy allows.

```

(or whatever it actually does...)

**Comment by zaro0508** [comment]
> Looking at this script it's not immediately clear what it's for. Could you add a comment? Something like:
> 
> ```
> This script is run on an EC2 instance upon start up to add its own address to the list of servers that the (reverse?? / forward??) proxy allows.
> ```
> 
> (or whatever it actually does...)

@ahayden created this script so maybe he can provide a description for us?

**Comment by ahayden** [comment]
This script adds a route in the Apache config for web requests with the URI that identifies the notebook... The path of this request gets rewritten by the proxy so that information identifying the notebook gets stripped out before the traffic is received by the notebook web server. I think we did it this way because the Apache module we use for rewrite did not support regular expressions.

**Comment by zaro0508** [comment]
thanks @ahayden, your description has been incorporated into the script.

**Review by tthyer — APPROVED** [review]

**Pull request merged**
